[package]
name = "gat-core"
version = "0.5.7"
edition = "2021"

[features]
default = []
wasm = []

[dependencies]
anyhow = "1.0"
faer = "0.17"
once_cell = "1"
petgraph = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
