[package]
name = "gat-gui"
version = "0.1.2"
edition = "2021"

[dependencies]
gat-core = { path = "../gat-core" }
gat-viz = { path = "../gat-viz" }
anyhow = "1.0"

[[bin]]
name = "gat-gui"
path = "src/bin/main.rs"
