[package]
name = "gat-gui"
version = "0.3.1"
edition = "2021"

[dependencies]
gat-core = { path = "../gat-core" }
gat-viz = { path = "../gat-viz" }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "gat-gui"
path = "src/bin/main.rs"
